[workspace]
members = [
  "crates/anonymization",
  "crates/cloudproof",
  "crates/cover_crypt",
  "crates/ffi_utils",
  "crates/findex",
  "crates/fpe",
]

[workspace.dependencies]
base64 = "0.21.0"
# cosmian_crypto_core = {git = "https://github.com/Cosmian/crypto_core.git", branch="develop"}
cosmian_crypto_core = "7.0"
cosmian_ffi_utils = "0.1.1"
hex = "0.4.3"
js-sys = "0.3"
pyo3 = { version = "0.18", features = ["extension-module", "abi3", "abi3-py37", "generate-import-lib"] }
rand = "0.8"
wasm-bindgen = "0.2.84"

[profile.release]
lto = true
strip = true
