[workspace]
members = [
  "crates/cover_crypt",
  "crates/ffi_utils",
  "crates/findex",
  "crates/fpe",
]

[workspace.dependencies]
cosmian_crypto_core = "7.0"

[profile.release]
lto = true
strip = true
