[workspace]
members = [
  "crates/anonymization",
  "crates/cloudproof",
  "crates/cover_crypt",
  "crates/ffi_utils",
  "crates/findex",
  "crates/fpe",
]

[workspace.dependencies]
cosmian_crypto_core = "7.0"
js-sys = "0.3"
pyo3 = { version = "0.18", features = ["extension-module", "abi3", "abi3-py37", "generate-import-lib"] }
wasm-bindgen = "0.2.84"

[profile.release]
lto = true
strip = true
