[package]
name = "cosmian_anonymization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8"
fpe = { git = "https://github.com/Cosmian/cosmian_fpe" }
itertools = "0.10"
num-bigint = { version = "0.4", default-features = false }
num-integer = { version = "0.1", default-features = false }
num-traits = { version = "0.2", default-features = false }
thiserror = "1.0"


[dev-dependencies]
rand = "0.8"
rand_distr = "0.4"
rand_chacha = "0.3"
