[package]
name = "cloudproof_rust"
version = "0.1.0"
edition = "2021"
authors = ["Bruno Grieder<bruno.grieder@cosmian.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version ="0.2", features = ["js"] }

# Optional dependencies
aes = { version = "0.8", optional = true }
cosmian_cover_crypt = { git = "https://github.com/Cosmian/cover_crypt.git", branch = "feature/cloudproof_rust", features = ["serialization"], optional = true }
cosmian_crypto_core = { git = "https://github.com/Cosmian/crypto_core.git", branch = "feature/cleanup", optional = true }
fpe = { git = "https://github.com/Cosmian/cosmian_fpe", optional = true }
itertools = { version = "0.10", optional = true }
js-sys = { version = "0.3", optional = true }
lazy_static = { version = "1.4.0", optional = true }
num-bigint = { version = "0.4", default-features = false, optional = true }
num-integer = { version = "0.1", default-features = false, optional = true }
num-traits = { version = "0.2", default-features = false, optional = true }
pyo3 = { version = "0.17", features = ["extension-module", "abi3", "abi3-py37", "generate-import-lib"], optional = true }
rand = { version = "0.8", optional = true }
rand_distr = { version = "0.4", optional = true }
rand_chacha = { version = "0.3", optional = true }
serde_json = { version = "1.0", optional = true }
wasm-bindgen = { version = "0.2", features = [
    "serde-serialize",
], optional = true }

[dev-dependencies]
criterion = { version = "0.4", default-features = false }
rand = "0.8"
rand_distr = "0.4"
rand_chacha = "0.3"
wasm-bindgen-test = "0.3"


[features]
fpe = ["dep:fpe", "aes", "itertools", "num-bigint", "num-integer", "num-traits", "rand", "rand_distr", "rand_chacha"]
dylib = ["rand", "rand_distr", "rand_chacha"]
wasm = ["wasm-bindgen", "js-sys"]
#findex = ["cosmian_findex"]
cover_crypt = ["cosmian_cover_crypt", "cosmian_crypto_core", "serde_json"]
ffi = ["lazy_static"]
python = ["pyo3"]


[[bench]]
harness = false
name = "benches"
