[package]
name = "cloudproof_fpe"
version = "0.1.0"
authors = [
  "Théophile Brézot<theophile.brezot@cosmian.com>",
]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Cosmian Cloudproof FPE library"

[lib]
crate-type = ["cdylib", "rlib"]
name = "cloudproof_fpe"

[features]
wasm_bindgen = []

[dependencies]
aes = { version = "0.8" }
fpe = { git = "https://github.com/Cosmian/cosmian_fpe" }
itertools = { version = "0.10" }
num-bigint = { version = "0.4", default-features = false }
num-integer = { version = "0.1", default-features = false }
num-traits = { version = "0.2", default-features = false }

[dev-dependencies]
criterion = "0.4.0"
rand =  "0.8"
rand_chacha =  "0.3"
rand_distr =  "0.4"
