[package]
name = "cloudproof_cover_crypt"
version = "0.1.0"
authors = [
  "Théophile Brézot<theophile.brezot@cosmian.com>",
]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Cosmian CoverCrypt Cloudproof library"

[lib]
crate-type = ["cdylib", "rlib"]
name = "cloudproof_cover_crypt"

[features]
ffi = ["cosmian_ffi_utils", "lazy_static"]
python = ["pyo3"]
wasm = ["js-sys", "wasm-bindgen"]

[dependencies]
cosmian_crypto_core.workspace = true
cosmian_cover_crypt = { git = "https://github.com/Cosmian/cover_crypt.git", branch = "feature/cloudproof_rust", features = ["serialization"] }
serde_json = "1.0.93"

# Optional dependencies
cosmian_ffi_utils = { path = "../ffi_utils", optional = true }
js-sys = { version = "0.3.61", optional = true }
lazy_static = { version = "1.4.0", optional = true }
pyo3 = { version = "0.18.1", features = ["extension-module"], optional = true }
wasm-bindgen = { version = "0.2.84", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
