[package]
name = "cloudproof_cover_crypt"
version = "0.1.0"
authors = [
  "Théophile Brézot<theophile.brezot@cosmian.com>",
]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Cosmian CoverCrypt Cloudproof library"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
name = "cloudproof_cover_crypt"

[features]
ffi = ["cosmian_ffi", "lazy_static"]
python = ["pyo3"]
wasm_bindgen = ["js-sys", "wasm-bindgen"]

[dependencies]
base64 = { workspace = true }
cosmian_cover_crypt = { git = "https://github.com/Cosmian/cover_crypt.git", rev = "7438d3d", features = ["interface"] }
cosmian_crypto_core = "5.0"
cosmian_ffi = { path = "../ffi_utils", optional = true }
hex = { workspace = true }
js-sys = { workspace = true, optional = true }
lazy_static = { version = "1.4", optional = true }
leb128 = { workspace = true }
pqc_kyber = { version = "0.4", features = ["wasm", "hazmat"] }
pyo3 = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
zeroize = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
