[package]
name = "cloudproof_findex"
version = "4.0.0"
authors = ["Théophile Brézot<theophile.brezot@cosmian.com>"]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Cosmian Findex Cloudproof library"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
name = "cloudproof_findex"

[features]
cloud = ["reqwest", "base64"]
ffi = ["cosmian_ffi_utils", "base64", "serde_json", "tokio/rt-multi-thread"]
python = ["cloud", "futures", "pyo3", "tokio/rt-multi-thread"]
sqlite = ["base64", "faker_rand", "rand", "rusqlite", "serde", "serde_json"]
wasm_bindgen = [
  "cloud",
  "js-sys",
  "hex",
  "wasm-bindgen",
  "wasm-bindgen-futures",
]
default = []

[dependencies]
cosmian_crypto_core.workspace = true
cosmian_findex = "3.0"

# Optional dependencies
base64 = { version = "0.21.0", optional = true }
cosmian_ffi_utils = { version = "0.1.0", optional = true }
faker_rand = { version = "0.1", optional = true }
futures = { version = "0.3.26", optional = true }
hex = { version = "0.4.3", optional = true }
js-sys = { workspace = true, optional = true }
pyo3 = { workspace = true, features = ["extension-module"], optional = true }
rand = { version = "0.8", optional = true }
reqwest = { version = "0.11.14", features = ["rustls-tls"], default-features = false, optional = true }
rusqlite = { version = "0.28", features = ["bundled"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0.93", optional = true }
tokio = { version = "1.25.0", optional = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { version = "0.4.34", optional = true }

[dev-dependencies]
actix-rt = "2.8"
