[package]
name = "cloudproof_findex"
version = "0.1.0"
authors = [
  "Théophile Brézot<theophile.brezot@cosmian.com>",
]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Cosmian Findex Cloudproof library"

[lib]
crate-type = ["cdylib", "rlib"]
name = "cloudproof_findex"

[features]
cloud = ["reqwest", "base64"]
ffi = ["cosmian_ffi_utils", "base64", "serde_json", "tokio/rt-multi-thread"]
python = ["pyo3", "futures"]
wasm = ["js-sys", "hex", "wasm-bindgen", "wasm-bindgen-futures"]

[dependencies]
cosmian_crypto_core.workspace = true
cosmian_findex = { git = "https://github.com/Cosmian/findex.git", branch = "feature/cloudproof_rust" }

# Optional dependencies
base64 = { version = "0.21.0", optional = true }
cosmian_ffi_utils = { path = "../ffi_utils", optional = true }
futures = { version = "0.3.26", optional = true }
hex = { version = "0.4.3", optional = true }
js-sys = { version = "0.3.61", optional = true }
pyo3 = { version = "0.18.1", features = ["extension-module"], optional = true }
serde_json = { version = "1.0.93", optional = true }
tokio = { version = "1.25.0", optional = true }
wasm-bindgen = { version = "0.2.84", optional = true }
wasm-bindgen-futures = { version = "0.4.34", optional = true }
reqwest = { version = "0.11.14", optional = true }
