---
name: Benches on demand

on: workflow_dispatch

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@wasm_feature
    with:
      toolchain: stable
      force: true
