---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: stable
      kms-version: feature-pyo3-generic-request
      findex-cloud-version: 0.3.1
      branch-java: fix/rename_findex_trait
      branch-js: fix/rename_calbacks_to_backend
      branch-kms-js: v2.0.0
      branch-flutter: fix/use_insert_entry_in_compact
      branch-python: feature/kms-generics
      exclusions: --exclude=cloudproof_findex
    secrets: inherit
