---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: stable
      kms-version: ghcr.io/cosmian/kms:4.11.3
      findex-cloud-version: 0.3.1
      branch-java: feature/covercrypt_rekey
      branch-js: develop
      branch-kms-js: v3.1.2
      branch-flutter: develop
      branch-python: develop
      exclusions: --exclude=cloudproof_findex
    secrets: inherit
