---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: stable
      kms-version: 4.9.1
      findex-cloud-version: 0.3.1
      branch-java: develop
      branch-js: develop
      branch-kms-js: v2.0.0
      branch-flutter: develop
      branch-python: feature/findex_v6
      exclusions: --exclude=cloudproof_findex
    secrets: inherit
