---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: stable
      kms-version: 4.2.0
      branch-java: main
      branch-js: main
      branch-flutter: main
      branch-python: main
    secrets: inherit
