---
name: Cloudproof build

on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: nightly-2023-03-20
      kms-version: 4.3.3
      branch-java: update_findex_4
      branch-js: update_findex_4
      branch-flutter: v6.0.2
      branch-python: update_findex_4
    secrets: inherit
