---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: nightly-2023-03-20
      kms-version: cli-fixes
      branch-java: v5.0.0
      branch-js: v8.1.0
      branch-flutter: v6.0.2
      branch-python: cloudproof_rust_1.3.0
    secrets: inherit
