---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: stable
      kms-version: 4.5.0
      findex-cloud-version: 0.1.0
      branch-java: feature/use_findex_v5.0.0
      branch-js: v9.2.0
      branch-flutter: feature/findex_5
      branch-python: v4.1.0
    secrets: inherit
