---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: nightly-2023-06-27
      kms-version: 4.4.3
      findex-cloud-version: 0.1.0
      branch-java: v6.0.0
      branch-js: develop
      branch-flutter: develop
      branch-python: v4.0.2
    secrets: inherit
