---
name: Cloudproof build

on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: nightly-2023-03-20
      kms-version: 4.3.3
      branch-java: develop
      branch-js: develop
      branch-flutter: fix_errors
      branch-python: upgrade_findex_for_ci
    secrets: inherit
