---
name: Cloudproof build

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@anonymization
    with:
      project-name: cloudproof_rust
      toolchain: nightly-2023-03-20
      kms-version: 4.3.3
      branch-java: develop
      branch-js: feature/anonymization
      branch-flutter: develop
      branch-python: feature/anonymization
    secrets: inherit
