---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@findex_ffi_instance
    with:
      project-name: cloudproof_rust
      toolchain: stable
      kms-version: 4.9.1
      findex-cloud-version: 0.3.1
      branch-java: feature/findex_v6
      branch-js: feature/findex_v6
      branch-kms-js: v2.0.0
      branch-flutter: feature/findex_v6
      branch-python: develop
      exclusions: --exclude=cloudproof_findex
    secrets: inherit
