---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: stable
      kms-version: feat-edit_policy
      findex-cloud-version: 0.1.0
      branch-java: develop
      branch-js: v9.2.0
      branch-flutter: develop
      branch-python: feat/edit_policy
    secrets: inherit
