---
name: Cloudproof build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  cloudproof_rust:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof.yml@develop
    with:
      project-name: cloudproof_rust
      toolchain: nightly-2022-10-28
      kms-version: 4.3.3
      branch-java: feature/cloudproof_rust
      branch-js: feature/cloudproof_rust
      branch-flutter: develop
      branch-python: develop
    secrets: inherit
