---
name: CI checks

on: push

jobs:
  cargo-nursery-base:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-nursery-base.yml@develop
    with:
      toolchain: nightly-2023-03-20

  cargo-doc:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-doc.yml@develop
    with:
      toolchain: nightly-2023-03-20

  test_and_dry_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-semver-
          restore-keys: ${{ runner.os }}-cargo-semver-

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-06-27
          override: true

      - name: Run python tests
        run: |
          bash scripts/test_python.sh
