---
name: CI checks

on: push

jobs:
  cargo-nursery-base:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-nursery-base.yml@wasm_feature
    with:
      toolchain: stable
      exclusions: --exclude=cloudproof_findex

  cargo-doc:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-doc.yml@wasm_feature
    with:
      toolchain: stable
      exclusions: --exclude=cloudproof_findex

  test_and_dry_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-individual-tests-
          restore-keys: ${{ runner.os }}-individual-tests-

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run python tests
        run: |
          bash scripts/test_python.sh

      - name: FFI Static analysis for cloudproof_findex
        run: |
          cargo clippy --workspace -p cloudproof_findex --all-targets --features ffi -- -D warnings

      - name: Wasm Static analysis for cloudproof_findex
        run: |
          cargo clippy --workspace -p cloudproof_findex --all-targets --features wasm -- -D warnings

      - name: Python Static analysis for cloudproof_findex
        run: |
          cargo clippy --workspace -p cloudproof_findex --all-targets --features python -- -D warnings

      - name: FFI tests for cloudproof_findex
        run: |
          cargo test --release --workspace -p cloudproof_findex --all-targets --features ffi

      - name: Wasm tests for cloudproof_findex
        run: |
          cargo test --release --workspace -p cloudproof_findex --all-targets --features wasm
